command_timeout = 2000

[character]
success_symbol = "[](green)"
error_symbol = "[](red)"
vicmd_symbol = "[](green)"

[hostname]
ssh_symbol = " "
format = "[$ssh_symbol](bold blue) on [$hostname](bold blue) "

[directory]
read_only = "  "

[c]
symbol = ' '

[docker_context]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[rust]
symbol = " "
